GET https://localhost:7097/api/producto HTTP/1.1
Accept: application/json


POST https://api.sendgrid.com/v3/mail/send HTTP/1.1
Authorization: Bearer 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
Content-Type: application/json

{
  "categories": [
    "demo"
  ],
  "from": {
    "email": "diana_torres6@usmp.pe", //correo origen  settings\sender authentification
    "name": "Mail Service"
  },
  "personalizations": [
    {
      "to": [
        {
          "email": "diana.etg96@gmail.com", //correo destino variable
          "name": "Diana Torres"
        }
      ],
      "subject": "Hola"
    }
  ],
  "content": [
    {
      "type": "text/plain",
      "value": "Hola ahora ya uso sendgrid!"
    }
  ],
}